## Attribute information

absenteeism_at_work_dataset/UCI_ABS_TEXT.docx

## Import and Clean Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_csv('./absenteeism_at_work_dataset/Absenteeism_at_work.csv', sep=';')

In [3]:
raw_data.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   ...  Disciplinary failure  Education  Son  \
0                 239.554  ...                     0          1    2   
1                 239.554  ...                     1          1    1   
2                 239.554  ...                     0          1    0   
3                 239.554  ...                     0          1    2   
4                 239.554  ...                     0          1    2   

   Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0               1              0    1      90     172               30   
1               1              0    0      98     178               31   
2               1              0    0      89     170               31   
3               1              1    0      68     168               24   
4               1              0    1      90     172               30   

   Absenteeism time in hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2  

[5 rows x 21 columns]

In [4]:
raw_data.shape

(740, 21)

In [5]:
raw_data.columns

Index(['ID', 'Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Transportation expense', 'Distance from Residence to Work',
       'Service time', 'Age', 'Work load Average/day ', 'Hit target',
       'Disciplinary failure', 'Education', 'Son', 'Social drinker',
       'Social smoker', 'Pet', 'Weight', 'Height', 'Body mass index',
       'Absenteeism time in hours'],
      dtype='object')

O que precisa ser feito em termos de pré-processamento? Devemos examinar os dados cuidadosamente. Mas antes disso, vamos fazer uma cópia do nosso dataset.

In [6]:
df = raw_data.copy()

In [7]:
# Permitir que mais linhas sejam exibidas
#pd.options.display.max_rows = None
#pd.options.display.max_columns = None

In [8]:
display(df)

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0    11                  26                 7                3        1   
1    36                   0                 7                3        1   
2     3                  23                 7                4        1   
3     7                   7                 7                5        1   
4    11                  23                 7                5        1   
..   ..                 ...               ...              ...      ...   
735  11                  14                 7                3        1   
736   1                  11                 7                3        1   
737   4                   0                 0                3        1   
738   8                   0                 0                4        2   
739  35                   0                 0                6        3   

     Transportation expense  Distance from Residence to Work  Service time  \
0                       289                               36            13   
1                       118                               13            18   
2                       179                               51            18   
3                       279                                5            14   
4                       289                               36            13   
..                      ...                              ...           ...   
735                     289                               36            13   
736                     235                               11            14   
737                     118                               14            13   
738                     231                               35            14   
739                     179                               45            14   

     Age  Work load Average/day   ...  Disciplinary failure  Education  Son  \
0     33                 239.554  ...                     0          1    2   
1     50                 239.554  ...                     1          1    1   
2     38                 239.554  ...                     0          1    0   
3     39                 239.554  ...                     0          1    2   
4     33                 239.554  ...                     0          1    2   
..   ...                     ...  ...                   ...        ...  ...   
735   33                 264.604  ...                     0          1    2   
736   37                 264.604  ...                     0          3    1   
737   40                 271.219  ...                     0          1    1   
738   39                 271.219  ...                     0          1    2   
739   53                 271.219  ...                     0          1    1   

     Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0                 1              0    1      90     172               30   
1                 1              0    0      98     178               31   
2                 1              0    0      89     170               31   
3                 1              1    0      68     168               24   
4                 1              0    1      90     172               30   
..              ...            ...  ...     ...     ...              ...   
735               1              0    1      90     172               30   
736               0              0    1      88     172               29   
737               1              0    8      98     170               34   
738               1              0    2     100     170               35   
739               0              0    1      77     175               25   

     Absenteeism time in hours  
0                            4  
1                            0  
2                            2  
3                            4  
4                            2  
..                         ...  
735                          8  
736                          4  
737     

In [9]:
df.rename(columns={
    'Reason for absence': 'Reason',
    'Month of absence': 'Month',
    'Day of the week': 'Weekday',
    'Seasons': 'Season',
    'Transportation expense': 'TransportExpense',
    'Distance from Residence to Work': 'Distance',
    'Service time': 'ServiceTime',
    'Work load Average/day ': 'Workload',
    'Hit target': 'HitTarget',
    'Disciplinary failure': 'Failure',
    'Son': 'Child',
    'Social drinker': 'Drinker',
    'Social smoker': 'Smoker',
    'Body mass index': 'BMI',
    'Absenteeism time in hours': 'AbsHours'
}, inplace=True)
df.head()

ID  Reason  Month  Weekday  Season  TransportExpense  Distance  \
0  11      26      7        3       1               289        36   
1  36       0      7        3       1               118        13   
2   3      23      7        4       1               179        51   
3   7       7      7        5       1               279         5   
4  11      23      7        5       1               289        36   

   ServiceTime  Age  Workload  ...  Failure  Education  Child  Drinker  \
0           13   33   239.554  ...        0          1      2        1   
1           18   50   239.554  ...        1          1      1        1   
2           18   38   239.554  ...        0          1      0        1   
3           14   39   239.554  ...        0          1      2        1   
4           13   33   239.554  ...        0          1      2        1   

   Smoker  Pet  Weight  Height  BMI  AbsHours  
0       0    1      90     172   30         4  
1       0    0      98     178   31         0  
2       0    0      89     170   31         2  
3       1    0      68     168   24         4  
4       0    1      90     172   30         2  

[5 rows x 21 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                740 non-null    int64  
 1   Reason            740 non-null    int64  
 2   Month             740 non-null    int64  
 3   Weekday           740 non-null    int64  
 4   Season            740 non-null    int64  
 5   TransportExpense  740 non-null    int64  
 6   Distance          740 non-null    int64  
 7   ServiceTime       740 non-null    int64  
 8   Age               740 non-null    int64  
 9   Workload          740 non-null    float64
 10  HitTarget         740 non-null    int64  
 11  Failure           740 non-null    int64  
 12  Education         740 non-null    int64  
 13  Child             740 non-null    int64  
 14  Drinker           740 non-null    int64  
 15  Smoker            740 non-null    int64  
 16  Pet               740 non-null    int64  
 1

Todos os atributos são *int* ou *float*, mas pela descrição, algumas são categorias

### Reason of Absence

In [11]:
df['Reason'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [12]:
df['Reason'].min()

0

In [13]:
df['Reason'].max()

28

In [14]:
len(df['Reason'].unique())

28

In [15]:
sorted(df['Reason'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

A categoria 20 (External causes of morbidity and mortality) não aparece nenhuma vez.

In [16]:
df['Reason'] = df['Reason'].astype('category')

In [17]:
df['Reason'].dtypes

CategoricalDtype(categories=[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
                  15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28],
, ordered=False)

### Month, Weekday and Season

In [18]:
df['Month'].unique()

array([ 7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  0])

In [19]:
len(df['Month'].unique())

13

Temos uma categoria 0 para o mês e provavelmente os registros com este valor estão corrompidos. **Vamos remover essas linhas**

In [20]:
df[df['Month'] == 0]

ID Reason  Month  Weekday  Season  TransportExpense  Distance  \
737   4      0      0        3       1               118        14   
738   8      0      0        4       2               231        35   
739  35      0      0        6       3               179        45   

     ServiceTime  Age  Workload  ...  Failure  Education  Child  Drinker  \
737           13   40   271.219  ...        0          1      1        1   
738           14   39   271.219  ...        0          1      2        1   
739           14   53   271.219  ...        0          1      1        0   

     Smoker  Pet  Weight  Height  BMI  AbsHours  
737       0    8      98     170   34         0  
738       0    2     100     170   35         0  
739       0    1      77     175   25         0  

[3 rows x 21 columns]

In [21]:
df = df[df['Month'] != 0]

In [22]:
df.shape

(737, 21)

In [23]:
df['Weekday'].unique()

array([3, 4, 5, 6, 2])

In [24]:
df['Season'].unique()

array([1, 4, 2, 3])

In [25]:
df['Month'] = df['Month'].astype('category')
df['Weekday'] = df['Weekday'].astype('category')
df['Season'] = df['Season'].astype('category')

### Education

In [26]:
df['Education'].unique()

array([1, 3, 2, 4])

In [29]:
df.dtypes

ID                     int64
Reason              category
Month               category
Weekday             category
Season              category
TransportExpense       int64
Distance               int64
ServiceTime            int64
Age                    int64
Workload             float64
HitTarget              int64
Failure                int64
Education           category
Child                  int64
Drinker                int64
Smoker                 int64
Pet                    int64
Weight                 int64
Height                 int64
BMI                    int64
AbsHours               int64
dtype: object

## Creating new Columns

### Nova coluna para Season

In [30]:
season_mapping = {1: 'Summer', 2: 'Autumn', 3: 'Winter', 4: 'Spring'}
df.loc[:, 'season_name'] = df['Season'].map(season_mapping)

In [31]:
df['season_name'].unique()

['Summer', 'Spring', 'Autumn', 'Winter']
Categories (4, object): ['Summer', 'Spring', 'Autumn', 'Winter']

### Nova coluna para Month

In [33]:
import calendar

In [34]:
df['month_name'] = df['Month'].apply(lambda x: calendar.month_abbr[x])

In [35]:
df[0:100][['Month', 'month_name']]

Month month_name
0      7        Jul
1      7        Jul
2      7        Jul
3      7        Jul
4      7        Jul
..   ...        ...
95    11        Nov
96    11        Nov
97    11        Nov
98    12        Dec
99    12        Dec

[100 rows x 2 columns]

### Nova coluna para Reasons

...

### Nova coluna para Education

In [36]:
df['Education'].value_counts()

1    608
3     79
2     46
4      4
Name: Education, dtype: int64

In [37]:
df.loc[df['Education'] == 1, 'education_name'] = 'High school'
df.loc[df['Education'] == 2, 'education_name'] = 'Graduate'
df.loc[df['Education'] == 3, 'education_name'] = 'Post graduate'
df.loc[df['Education'] == 4, 'education_name'] = 'Master and doctor'

In [39]:
df[['Education', 'education_name']]

Education education_name
0           1    High school
1           1    High school
2           1    High school
3           1    High school
4           1    High school
..        ...            ...
732         1    High school
733         1    High school
734         1    High school
735         1    High school
736         3  Post graduate

[737 rows x 2 columns]

## Checkpoint

In [40]:
df_mod = df.copy()

## Homework

Com base nas informações do dataset, nas colunas Month e Weekday, conseguimos descobrir o ano em que cada registro foi inserido? Se sim, crie uma coluna chamada "year" com seus respectivos valores.

In [43]:
df[['Month', 'Weekday']]

Month Weekday
0       7       3
1       7       3
2       7       4
3       7       5
4       7       5
..    ...     ...
732     7       4
733     7       4
734     7       2
735     7       3
736     7       3

[737 rows x 2 columns]