# EXPLORATORY DATA ANALYSIS
Using Absenteeism at work An UCI dataset

## About Dataset

### Abstract
The database was created with records of absenteeism at work from July 2007 to July 2010 at a courier company in Brazil. Absenteeism at work An UCI dataset on link data set : https://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work


    Data Set Characteristics  : Multivariate, Time-Series                Number of Instances   : 740 
    Attribute Characteristics : Integer, Real                            Number of Attributes  : 21
    Associated Tasks          : Classification, Clustering               Missing Values?       : N/A


### Metadata
    Usage Information             License                     CC0: Public Domain (https://creativecommons.org/publicdomain/zero/1.0//)
                                  Visibility                  visibility Public
    
    Provenance                    Sources                     (https://archive.ics.uci.edu/ml/datasets/Absenteeism+at+work)

    Maintainers                   Dataset owner               rahul bhaskaran (https://www.kaggle.com/loganalive)

    Updates                       Expected update frequency   Never
                                  Last updated                2018-04-27                 
                                  Date created                2018-04-27                  
                                  Current version             Version 1

### Data set information
The data set allows for several new combinations of attributes and attribute exclusions, or the modification of the attribute type (categorical, integer, or real) depending on the purpose of the research.The data set (Absenteeism at work - Part I) was used in academic research at the Universidade Nove de Julho - Postgraduate Program in Informatics and Knowledge Management.

### Attribute Information
  1. Individual identification (ID)
  2. Reason for absence (ICD).
    
    Absences attested by the International Code of Diseases (ICD) stratified into 21 categories (I to XXI) as follows:

    
    I Certain infectious and parasitic diseases
    II Neoplasms
    III Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
    IV Endocrine, nutritional and metabolic diseases
    V Mental and behavioural disorders
    VI Diseases of the nervous system
    VII Diseases of the eye and adnexa
    VIII Diseases of the ear and mastoid process
    IX Diseases of the circulatory system
    X Diseases of the respiratory system
    XI Diseases of the digestive system
    XII Diseases of the skin and subcutaneous tissue
    XIII Diseases of the musculoskeletal system and connective tissue
    XIV Diseases of the genitourinary system
    XV Pregnancy, childbirth and the puerperium
    XVI Certain conditions originating in the perinatal period
    XVII Congenital malformations, deformations and chromosomal abnormalities
    XVIII Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified
    XIX Injury, poisoning and certain other consequences of external causes
    XX External causes of morbidity and mortality
    XXI Factors influencing health status and contact with health services.

    And 7 categories without (CID) 
    patient follow-up (22), 
    medical consultation (23), 
    blood donation (24), 
    laboratory examination (25), 
    unjustified absence (26), 
    physiotherapy (27), 
    dental consultation (28).
        
  3. Month of absence
  4. Day of the week (Monday (2), Tuesday (3), Wednesday (4), Thursday (5), Friday (6))
  5. Seasons (summer (1), autumn (2), winter (3), spring (4))
  6. Transportation expense
  7. Distance from Residence to Work (kilometers)
  8. Service time
  9. Age
  10. Work load Average/day
  11. Hit target
  12. Disciplinary failure (yes=1; no=0)
  13. Education (high school (1), graduate (2), postgraduate (3), master and doctor (4))
  14. Son (number of children)
  15. Social drinker (yes=1; no=0)
  16. Social smoker (yes=1; no=0)
  17. Pet (number of pet)
  18. Weight
  19. Height
  20. Body mass index
  21. Absenteeism time in hours (target)


## Import and Clean Data

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive


In [2]:
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [3]:
raw_data = pd.read_csv('/content/gdrive/MyDrive/IFSP - Campinas/Pós - Ciência de Dados/1-D1INT - Introdução à Ciência de Dados/1 - Aulas/Aula 04 - EDA/input/Absenteeism_at_work.csv', sep=';')

In [4]:
raw_data.head()

ID  Reason for absence  ...  Body mass index  Absenteeism time in hours
0  11                  26  ...               30                          4
1  36                   0  ...               31                          0
2   3                  23  ...               31                          2
3   7                   7  ...               24                          4
4  11                  23  ...               30                          2

[5 rows x 21 columns]

In [5]:
raw_data.shape

(740, 21)

In [6]:
raw_data.columns

Index(['ID', 'Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Transportation expense', 'Distance from Residence to Work',
       'Service time', 'Age', 'Work load Average/day ', 'Hit target',
       'Disciplinary failure', 'Education', 'Son', 'Social drinker',
       'Social smoker', 'Pet', 'Weight', 'Height', 'Body mass index',
       'Absenteeism time in hours'],
      dtype='object')

O que precisa ser feito em termos de pré-processamento? Devemos examinar os dados cuidadosamente. Mas antes disso, vamos fazer uma cópia do nosso dataset.

In [7]:
df = raw_data.copy()

In [8]:
#Permitir que mais linhas sejam exibidas
pd.options.display.max_rows = 100

In [9]:
display(df)

ID  Reason for absence  ...  Body mass index  Absenteeism time in hours
0    11                  26  ...               30                          4
1    36                   0  ...               31                          0
2     3                  23  ...               31                          2
3     7                   7  ...               24                          4
4    11                  23  ...               30                          2
..   ..                 ...  ...              ...                        ...
735  11                  14  ...               30                          8
736   1                  11  ...               29                          4
737   4                   0  ...               34                          0
738   8                   0  ...               35                          0
739  35                   0  ...               25                          0

[740 rows x 21 columns]

Primeiro vamos renomear as colunas para facilitar a manipulação de dados.

In [10]:
df.rename(columns={'Reason for absence': 'Reason', 'Month of absence': 'Month', 'Day of the week': 'Weekday',
                   'Seasons': 'Season', 'Disciplinary failure': 'Failure', 'Transportation expense': 'TransportExpense',
                   'Distance from Residence to Work': 'Distance', 'Service time': 'ServiceTime', 'Work load Average/day ': 'Workload',
                   'Hit target': 'HitTarget', 'Son': 'Child', 'Social drinker': 'Drinker', 'Social smoker': 'Smoker', 'Body mass index': 'BMI',
                   'Absenteeism time in hours': 'AbsHours'}, inplace = True)
df.head(10)

ID  Reason  Month  Weekday  Season  ...  Pet  Weight  Height  BMI  AbsHours
0  11      26      7        3       1  ...    1      90     172   30         4
1  36       0      7        3       1  ...    0      98     178   31         0
2   3      23      7        4       1  ...    0      89     170   31         2
3   7       7      7        5       1  ...    0      68     168   24         4
4  11      23      7        5       1  ...    1      90     172   30         2
5   3      23      7        6       1  ...    0      89     170   31         2
6  10      22      7        6       1  ...    4      80     172   27         8
7  20      23      7        6       1  ...    0      65     168   23         4
8  14      19      7        2       1  ...    0      95     196   25        40
9   1      22      7        2       1  ...    1      88     172   29         8

[10 rows x 21 columns]

Suponha que queremos saber a quantidade de missing values e o conjunto de dados é BEM MAIOR do que este.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   ID                740 non-null    int64  
 1   Reason            740 non-null    int64  
 2   Month             740 non-null    int64  
 3   Weekday           740 non-null    int64  
 4   Season            740 non-null    int64  
 5   TransportExpense  740 non-null    int64  
 6   Distance          740 non-null    int64  
 7   ServiceTime       740 non-null    int64  
 8   Age               740 non-null    int64  
 9   Workload          740 non-null    float64
 10  HitTarget         740 non-null    int64  
 11  Failure           740 non-null    int64  
 12  Education         740 non-null    int64  
 13  Child             740 non-null    int64  
 14  Drinker           740 non-null    int64  
 15  Smoker            740 non-null    int64  
 16  Pet               740 non-null    int64  
 1

Podemos ver que todas as colunas têm exatamente 740 valores. Isso significa que **não temos** valores faltantes (missing values).

### Change the appropriate data types of the columns

In [12]:
df.dtypes

ID                    int64
Reason                int64
Month                 int64
Weekday               int64
Season                int64
TransportExpense      int64
Distance              int64
ServiceTime           int64
Age                   int64
Workload            float64
HitTarget             int64
Failure               int64
Education             int64
Child                 int64
Drinker               int64
Smoker                int64
Pet                   int64
Weight                int64
Height                int64
BMI                   int64
AbsHours              int64
dtype: object

Todos os atributos estão como inteiros ou float. Mas se analisarmos o dicionário de dados, percebemos que existem variáveis categóricas e booleanas.


**Reason of Abesence**

In [13]:
df['Reason'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16])

In [14]:
df['Reason'].min()

0

In [15]:
df['Reason'].max()

28

In [16]:
len(df['Reason'].unique())

28

Parece que temos uma categoria que não aparece na base de dados. Qual é?

In [17]:
sorted(df['Reason'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

A categoria 20, External causes of morbidity and mortality, não aparece nenhuma vez. Voltaremos a manipular esta coluna quando estivermos preparando a base de dados para aplicar algum algoritmo de ML.

In [18]:
df['Reason'] = df['Reason'].astype('category')

In [19]:
df['Reason'].dtypes

CategoricalDtype(categories=[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
                  15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28],
                 ordered=False)

**Month, Weekday and Season**

In [20]:
df['Month'].unique()

array([ 7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  0])

In [21]:
len(df['Month'].unique())

13

Temos uma categoria 0 para representar o mês e provavelmente os registros com este valor estão corrompidos. **Vamos remover essas linhas.**

In [22]:
df[df['Month']==0]

ID Reason  Month  Weekday  Season  ...  Pet  Weight  Height  BMI  AbsHours
737   4      0      0        3       1  ...    8      98     170   34         0
738   8      0      0        4       2  ...    2     100     170   35         0
739  35      0      0        6       3  ...    1      77     175   25         0

[3 rows x 21 columns]

In [23]:
df = df[df['Month'] != 0]

In [24]:
df.shape

(737, 21)

In [25]:
#Day of the week (Monday (2), Tuesday (3), Wednesday (4), Thursday (5), Friday (6))
df['Weekday'].unique()

array([3, 4, 5, 6, 2])

In [26]:
#Seasons (summer (1), autumn (2), winter (3), spring (4))
df['Season'].unique()

array([1, 4, 2, 3])

In [27]:
df['Month'] = df['Month'].astype('category')
df['Weekday'] = df['Weekday'].astype('category')
df['Season'] = df['Season'].astype('category')

**Education**

In [28]:
df['Education'].unique()

array([1, 3, 2, 4])

In [29]:
df['Education'] = df['Education'].astype('category')

In [30]:
df.dtypes

ID                     int64
Reason              category
Month               category
Weekday             category
Season              category
TransportExpense       int64
Distance               int64
ServiceTime            int64
Age                    int64
Workload             float64
HitTarget              int64
Failure                int64
Education           category
Child                  int64
Drinker                int64
Smoker                 int64
Pet                    int64
Weight                 int64
Height                 int64
BMI                    int64
AbsHours               int64
dtype: object

In [31]:
df['Workload'].max()

378.884

In [32]:
df['Workload'].mean()

271.49133921302604

In [33]:
df['HitTarget'].unique()

array([ 97,  92,  93,  95,  99,  96,  94,  98,  81,  88, 100,  87,  91])

### Creating new columns

Para realizar uma melhor Análise Exploratória dos Dados, é preciso adicionar algumas colunas para visualização.

**Nova coluna para Season**

In [34]:
season_mapping = {1:'Summer', 2:'Autumn', 3:'Winter', 4:'Spring'}
df.loc[:,'season_name'] = df['Season'].map(season_mapping)

In [35]:
df['season_name'].unique()

['Summer', 'Spring', 'Autumn', 'Winter']
Categories (4, object): ['Summer', 'Spring', 'Autumn', 'Winter']

**Nova coluna para Month**

In [36]:
import calendar

In [37]:
df['month_name'] =  df['Month'].apply(lambda x: calendar.month_abbr[x])

In [38]:
df[0:100][['Month', 'month_name']]

Month month_name
0      7        Jul
1      7        Jul
2      7        Jul
3      7        Jul
4      7        Jul
5      7        Jul
6      7        Jul
7      7        Jul
8      7        Jul
9      7        Jul
10     7        Jul
11     7        Jul
12     7        Jul
13     7        Jul
14     7        Jul
15     7        Jul
16     7        Jul
17     7        Jul
18     7        Jul
19     8        Aug
20     8        Aug
21     8        Aug
22     8        Aug
23     8        Aug
24     8        Aug
25     8        Aug
26     8        Aug
27     8        Aug
28     8        Aug
29     8        Aug
30     8        Aug
31     8        Aug
32     8        Aug
33     8        Aug
34     8        Aug
35     8        Aug
36     8        Aug
37     8        Aug
38     8        Aug
39     8        Aug
40     9        Sep
41     9        Sep
42     9        Sep
43     9        Sep
44     9        Sep
45     9        Sep
46     9        Sep
47     9        Sep
48     9        Sep
49     9        Sep
50     9        Sep
51     9        Sep
52     9        Sep
53     9        Sep
54     9        Sep
55     9        Sep
56     9        Sep
57     9        Sep
58     9        Sep
59     9        Sep
60     9        Sep
61     9        Sep
62    10        Oct
63    10        Oct
64    10        Oct
65    10        Oct
66    10        Oct
67    10        Oct
68    10        Oct
69    10        Oct
70    10        Oct
71    10        Oct
72    10        Oct
73    10        Oct
74    10        Oct
75    10        Oct
76    10        Oct
77    10        Oct
78    10        Oct
79    10        Oct
80    11        Nov
81    11        Nov
82    11        Nov
83    11        Nov
84    11        Nov
85    11        Nov
86    11        Nov
87    11        Nov
88    11        Nov
89    11        Nov
90    11        Nov
91    11        Nov
92    11        Nov
93    11        Nov
94    11        Nov
95    11        Nov
96    11        Nov
97    11        Nov
98    12        Dec
99    12        Dec

**Nova coluna para Reason**

In [39]:
reason_mapping = {
    0: 'Unknown',
    1: 'Certain infectious and parasitic diseases',
    2: 'Neoplasms',
    3: 'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism',
    4: 'Endocrine, nutritional and metabolic diseases',
    5: 'Mental and behavioural disorders',
    6: 'Diseases of the nervous system',
    7: 'Diseases of the eye and adnexa',
    8: 'Diseases of the ear and mastoid process',
    9: 'Diseases of the circulatory system',
    10: 'Diseases of the respiratory system',
    11: 'Diseases of the digestive system',
    12: 'Diseases of the skin and subcutaneous tissue',
    13: 'Diseases of the musculoskeletal system and connective tissue',
    14: 'Diseases of the genitourinary system',
    15: 'Pregnancy, childbirth and the puerperium',
    16: 'Certain conditions originating in the perinatal period',
    17: 'Congenital malformations, deformations and chromosomal abnormalities',
    18: 'Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified',
    19: 'Injury, poisoning and certain other consequences of external causes',
    20: 'External causes of morbidity and mortality',
    21: 'Factors influencing health status and contact with health services',
    22: 'Patient follow-up',
    23: 'Medical consultation',
    24: 'Blood donation',
    25: 'Laboratory examination',
    26: 'Unjustified absence',
    27: 'Physiotherapy',
    28: 'Dental consultation'
}
df.loc[:,'reason_description'] = df['Reason'].map(reason_mapping)

In [40]:
df[0:100][['Reason', 'reason_description']]

Reason                                 reason_description
0      26                                Unjustified absence
1       0                                            Unknown
2      23                               Medical consultation
3       7                     Diseases of the eye and adnexa
4      23                               Medical consultation
5      23                               Medical consultation
6      22                                  Patient follow-up
7      23                               Medical consultation
8      19  Injury, poisoning and certain other consequenc...
9      22                                  Patient follow-up
10      1          Certain infectious and parasitic diseases
11      1          Certain infectious and parasitic diseases
12     11                   Diseases of the digestive system
13     11                   Diseases of the digestive system
14     23                               Medical consultation
15     14               Diseases of the genitourinary system
16     23                               Medical consultation
17     21  Factors influencing health status and contact ...
18     11                   Diseases of the digestive system
19     23                               Medical consultation
20     10                 Diseases of the respiratory system
21     11                   Diseases of the digestive system
22     13  Diseases of the musculoskeletal system and con...
23     28                                Dental consultation
24     18  Symptoms, signs and abnormal clinical and labo...
25     25                             Laboratory examination
26     23                               Medical consultation
27     28                                Dental consultation
28     18  Symptoms, signs and abnormal clinical and labo...
29     23                               Medical consultation
30     18  Symptoms, signs and abnormal clinical and labo...
31     18  Symptoms, signs and abnormal clinical and labo...
32     23                               Medical consultation
33     18  Symptoms, signs and abnormal clinical and labo...
34     23                               Medical consultation
35     23                               Medical consultation
36     24                                     Blood donation
37     11                   Diseases of the digestive system
38     28                                Dental consultation
39     23                               Medical consultation
40     23                               Medical consultation
41     23                               Medical consultation
42     23                               Medical consultation
43     19  Injury, poisoning and certain other consequenc...
44     23                               Medical consultation
45     23                               Medical consultation
46     23                               Medical consultation
47     23                               Medical consultation
48     22                                  Patient follow-up
49     14               Diseases of the genitourinary system
50      0                                            Unknown
51      0                                            Unknown
52     23                               Medical consultation
53     23                               Medical consultation
54      0                                            Unknown
55      0                                            Unknown
56     18  Symptoms, signs and abnormal clinical and labo...
57     23                               Medical consultation
58      0                                            Unknown
59     23                               Medical consultation
60     23                               Medical consultation
61     23                               Medical consultation
62     23                               Medical consultation
63     23                               Medical consultation
64      0                             

**Nova coluna para Education**

In [41]:
df['Education'].value_counts()

1    608
3     79
2     46
4      4
Name: Education, dtype: int64

In [42]:
df.loc[(df['Education'] == 1),'education_name'] = 'High school'
df.loc[(df['Education'] == 2),'education_name'] = 'Graduate'
df.loc[(df['Education'] == 3),'education_name'] = 'Postgraduate'
df.loc[(df['Education'] == 4),'education_name'] = 'Master and doctor'

In [43]:
df[100:300][['Education', 'education_name']]

Education education_name
100         1    High school
101         3   Postgraduate
102         1    High school
103         1    High school
104         1    High school
..        ...            ...
295         3   Postgraduate
296         1    High school
297         1    High school
298         1    High school
299         3   Postgraduate

[200 rows x 2 columns]

**Reogazinar as colunas**

In [44]:
df.columns

Index(['ID', 'Reason', 'Month', 'Weekday', 'Season', 'TransportExpense',
       'Distance', 'ServiceTime', 'Age', 'Workload', 'HitTarget', 'Failure',
       'Education', 'Child', 'Drinker', 'Smoker', 'Pet', 'Weight', 'Height',
       'BMI', 'AbsHours', 'season_name', 'month_name', 'reason_description',
       'education_name'],
      dtype='object')

In [45]:
col_names_reordered = ['ID', 'Reason', 'reason_description', 'Month', 'month_name', 'Weekday', 'Season', 'season_name', 
                       'TransportExpense', 'Distance', 'ServiceTime', 'Age', 'Workload', 'HitTarget', 'Failure',
                       'Education', 'education_name', 'Child', 'Drinker', 'Smoker', 'Pet', 'Weight', 'Height',
                       'BMI', 'AbsHours']

In [46]:
df = df[col_names_reordered]
df.head()

ID Reason              reason_description  ... Height BMI AbsHours
0  11     26             Unjustified absence  ...    172  30        4
1  36      0                         Unknown  ...    178  31        0
2   3     23            Medical consultation  ...    170  31        2
3   7      7  Diseases of the eye and adnexa  ...    168  24        4
4  11     23            Medical consultation  ...    172  30        2

[5 rows x 25 columns]

### **Checkpoint**

In [47]:
df_mod = df.copy()

### Homework

Com base nas informações do dataset, nas colunas Month e Weekday, conseguimos descobrir o ano em que cada registro foi inserido? Se sim, crie uma coluna chamada "Year" com seus respectivos valores. 

## Exploratory Data Analysis

In [49]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 14
plt.rcParams['ytick.labelsize'] = 14

### Qual a média de horas de absenteísmo por idade?

### Qual a média de horas de absenteísmo por motivo (Reason)?